In [1]:
import pandas as pd

In [2]:
courses_df = pd.read_csv("class_data.csv")

In [3]:
courses_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CRN               148 non-null    int64
 1   Subject           148 non-null    object
 2   COURSE            148 non-null    int64
 3   TITLE             148 non-null    object
 4   COHORT            12 non-null     object
 5   TYPE              77 non-null     object
 6   SCHEDULE          104 non-null    object
 7   TIME IN           102 non-null    object
 8   TIME OUT          104 non-null    object
 9   PLATFORM          127 non-null    object
 10  INSTRUCTOR        148 non-null    object
 11  INSTRUCTOR EMAIL  148 non-null    object
dtypes: int64(2), object(10)
memory usage: 14.0+ KB

In [4]:
courses_df.head()

,CRN,Subject,COURSE,TITLE,COHORT,TYPE,SCHEDULE,TIME IN,TIME OUT,PLATFORM,INSTRUCTOR,INSTRUCTOR EMAIL
0,30151,BIOL,215,Organismal Biology,NaN,NaN,"M, W",11:10 AM,12:25 PM,4148,"Song, M",songm@smccd.edu
1,30151,BIOL,215,Organismal Biology,NaN,NaN,"M, W",2:10 PM,5:00 PM,7241,"Song, M",songm@smccd.edu
2,41373,BIOL,215,Organismal Biology,NaN,NaN,"M, W",11:10 AM,12:25 PM,4148,"Song, M",songm@smccd.edu
3,41373,BIOL,215,Organismal Biology,NaN,NaN,"T, Th",9:10 AM,11:50 AM,7241,"Song, M",songm@smccd.edu
4,48398,BIOL,215,Organismal Biology,NaN,NaN,"M, W",11:10 AM,12:25 PM,4148,"Song, M",songm@smccd.edu

In [5]:
courses_df = courses_df.drop_duplicates(subset="CRN")

In [6]:
courses_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 91 entries, 0 to 147
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CRN               91 non-null     int64
 1   Subject           91 non-null     object
 2   COURSE            91 non-null     int64
 3   TITLE             91 non-null     object
 4   COHORT            8 non-null      object
 5   TYPE              43 non-null     object
 6   SCHEDULE          70 non-null     object
 7   TIME IN           68 non-null     object
 8   TIME OUT          68 non-null     object
 9   PLATFORM          85 non-null     object
 10  INSTRUCTOR        91 non-null     object
 11  INSTRUCTOR EMAIL  91 non-null     object
dtypes: int64(2), object(10)
memory usage: 9.2+ KB

In [7]:
courses_df.head()

,CRN,Subject,COURSE,TITLE,COHORT,TYPE,SCHEDULE,TIME IN,TIME OUT,PLATFORM,INSTRUCTOR,INSTRUCTOR EMAIL
0,30151,BIOL,215,Organismal Biology,NaN,NaN,"M, W",11:10 AM,12:25 PM,4148,"Song, M",songm@smccd.edu
2,41373,BIOL,215,Organismal Biology,NaN,NaN,"M, W",11:10 AM,12:25 PM,4148,"Song, M",songm@smccd.edu
4,48398,BIOL,215,Organismal Biology,NaN,NaN,"M, W",11:10 AM,12:25 PM,4148,"Song, M",songm@smccd.edu
6,48537,BIOL,230,Introduction to Cell Biology,NaN,NaN,"M, W",12:10 PM,1:25 PM,7106,"Guth, S",guths@smccd.edu
8,48811,BIOL,230,Introduction to Cell Biology,NaN,NaN,"M, W",11:10 AM,1:25 PM,7106,"Guth, S",guths@smccd.edu

In [8]:
courses_df = courses_df.reset_index()

In [9]:
courses_df.head()

,index,CRN,Subject,COURSE,TITLE,COHORT,TYPE,SCHEDULE,TIME IN,TIME OUT,PLATFORM,INSTRUCTOR,INSTRUCTOR EMAIL
0,0,30151,BIOL,215,Organismal Biology,NaN,NaN,"M, W",11:10 AM,12:25 PM,4148,"Song, M",songm@smccd.edu
1,2,41373,BIOL,215,Organismal Biology,NaN,NaN,"M, W",11:10 AM,12:25 PM,4148,"Song, M",songm@smccd.edu
2,4,48398,BIOL,215,Organismal Biology,NaN,NaN,"M, W",11:10 AM,12:25 PM,4148,"Song, M",songm@smccd.edu
3,6,48537,BIOL,230,Introduction to Cell Biology,NaN,NaN,"M, W",12:10 PM,1:25 PM,7106,"Guth, S",guths@smccd.edu
4,8,48811,BIOL,230,Introduction to Cell Biology,NaN,NaN,"M, W",11:10 AM,1:25 PM,7106,"Guth, S",guths@smccd.edu

In [10]:
courses_df.to_csv("class_data clean.csv")